<?php
// Call MyFileTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'MyFileTest::main');
}

require_once 'vendor/autoload.php';

require_once 'MyFile.php';

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2007-08-12 at 19:25:50.
 */
class MyFileTest extends PHPUnit_Framework_TestSuite {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('MyFileTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function testSetFileName()
    {
        $file = new MyFile;

        $this->assertTrue($file->setFileName('newfile'));
        $this->assertTrue($file->setFileName('newfile1'));
        $this->assertTrue($file->setFileName('new_file'));
        $this->assertTrue($file->setFileName('new-file'));

        $this->assertFalse($file->setFileName(null));
        $this->assertFalse($file->setFileName('ThisFileNameIsVeryLongTooLongReallyTooLong'));
        $this->assertFalse($file->setFileName('NewFileWith.ext'));
        $this->assertFalse($file->setFileName('àfile'));
        $this->assertFalse($file->setFileName(1));
    }

    public function testSetExtension()
    {
        $file = new MyFile('newFile');

        $this->assertTrue($file->setExtension('txt'));

        $this->assertFalse($file->setExtension(null));
        $this->assertFalse($file->setExtension('abcdef'));
        $this->assertFalse($file->setExtension('é'));
        $this->assertFalse($file->setExtension(1));
    }

    public function testGetFileName()
    {
        $exceptedFileName = 'newFile';

        $file = new MyFile($exceptedFileName);

        $this->assertEquals($exceptedFileName, $file->getFileName());
    }

    public function testGetExtension()
    {
        $exceptedExtension = 'txt';

        $file = new MyFile('newFile', $exceptedExtension);

        $this->assertEquals($exceptedExtension, $file->getExtension());
    }
}

// Call MyFileTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'MyFileTest::main') {
    MyFileTest::main();
}
?>