version: "3.1"

services:
  openssh-server:
    container_name: openssh-server
    build:
      context: ./                                           # Utilisation du Dockerfile du dossier

    volumes:
      - ./banner-message.txt:/etc/motd                     # Message de bienvenue affiché à la connexion
    ports:
      - 2222:22
    restart: unless-stopped